### ISSUE TITLE
读取大数据库特别慢，有什么建议的解决方法吗

### ISSUE THREAD

**Issue by zhzaozao** [chencodeX/triplet-loss-pytorch#2]
读取大数据库特别慢，有什么建议的解决方法吗

**Comment by chencodeX** [comment]
多大的数据库，数据库的组织形式如何，具体在哪一步慢？

**Comment by zhzaozao** [comment]
我开始测了个5w类，每类大概100幅图发现特别慢。调试用的400类，每类200幅图，create_triplet_db里for key_index in range(len(lable_sample_anchor_keys)): 改成 for key_index in range(N_used): ，N_used=10随机采样。这个循环里耗费时间很大` while True:
                    sample_nagetive = None	
		    start = time.time()
                    for key, value in negative_db.items():`打时间看是消耗在for这句

这个除了减小negative_db的大小还有别的方式吗？

另外，我发现用你这个dataloader即使不用三元组lose训练结果也比pytorch随机load数据的效果好

**Comment by chencodeX** [comment]
我觉得如果你的样本质量够好的情况下， 你可以只创建一次triplet_db，随后使用一个变量保存一下，下一次迭代的过程中继续使用这个db的拷贝。避免重复生成的随机过程。

至于为何训练效果更好，我个人觉得可能是这种人为精心构造的数据样本，比起随机抽样，在训练过程中每一个batch样本之间的差异性更大一些。对于使用了BN或者mini batch SGD等方法的模型，样本间的方差更大，模型效果会更好。
