### ISSUE TITLE
你好，请问这个代码用的是哪个数据集？

### ISSUE THREAD

**Issue by junchengberry** [chencodeX/triplet-loss-pytorch#7]
你好，这个代码实现的非常好，能否把代码用的数据集的名字给我说一下，我想复现一下实验结果，非常感谢

**Comment by chencodeX** [comment]
一个云的细粒度分类，已经找不到了

**Comment by JJJTF** [comment]
麻烦把数据集名字说一下

**Comment by chencodeX** [comment]
https://www.datafountain.cn/special/guanyunshitian/competition
