### ISSUE TITLE
你好，代码出现死循环

### ISSUE THREAD

**Issue by 613he** [chencodeX/triplet-loss-pytorch#9]
data_loader.py的102行：
            while len(self.data_queue) < self.batch_size:
                time.sleep(0.2)
这个容易出现死循环。

**Comment by chencodeX** [comment]
可否提供更多的信息和日志，帮助我判断问题原因

**Comment by 613he** [comment]
> 可否提供更多的信息和日志，帮助我判断问题原因

多谢大佬，我排查到问题了，图片读取遇到脏数据会出现上述问题。
